@extends('base.base-dash-index')
@section('title', 'Jadwal Mingguan dan Pertemuan')
@section('menu', 'Jadwal Mingguan')
@section('submenu', 'Jadwal dan Pertemuan')
@section('urlmenu', '#')
@section('subdesc', 'Kelola pola mingguan dan hasilkan pertemuan semester')
@section('content')
<section class="section">
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($canManage)<div class="card mb-3"><div class="card-header"><h5>Buat Jadwal Mingguan — {{ $period->name }}</h5></div><div class="card-body"><form method="POST" action="{{ route($prefix.'master.jadwal-mingguan-store') }}" class="row g-3">@csrf
<div class="col-md-6"><label class="form-label">Penawaran</label><select name="penawaran_mata_kuliah_id" class="form-select" required><option value="">Pilih</option>@foreach($offerings as $item)<option value="{{ $item->id }}">{{ $item->masterMataKuliah->name }} — {{ $item->kelas->name }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Kelas</label><select name="kelas_id" class="form-select" required>@foreach($offerings->pluck('kelas')->unique('id') as $class)<option value="{{ $class->id }}">{{ $class->name }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Dosen</label><select name="dosen_id" class="form-select" required>@foreach($lecturers as $lecturer)<option value="{{ $lecturer->id }}">{{ $lecturer->dsn_name }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Ruang</label><select name="ruang_id" class="form-select" required>@foreach($rooms as $room)<option value="{{ $room->id }}">{{ $room->name }} ({{ $room->kapasitas }})</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Hari</label><select name="hari" class="form-select" required>@foreach(['Minggu','Senin','Selasa','Rabu','Kamis',"Jum'at",'Sabtu'] as $day)<option value="{{ $loop->index }}">{{ $day }}</option>@endforeach</select></div>
<div class="col-md-2"><label class="form-label">Mulai</label><input type="time" name="mulai" class="form-control" required></div><div class="col-md-2"><label class="form-label">Selesai</label><input type="time" name="selesai" class="form-control" required></div>
<div class="col-md-2 d-flex align-items-end"><div class="form-check mb-2"><input type="checkbox" name="override_conflict" value="1" class="form-check-input"><label class="form-check-label">Pengecualian</label></div></div><div class="col-12"><textarea name="alasan_pengecualian" class="form-control" placeholder="Alasan pengecualian bentrok (khusus Web Administrator)"></textarea></div><div class="col-12"><button class="btn btn-primary">Simpan jadwal</button></div>
</form></div></div>@endif
@if($canManage)<div class="card mb-3"><div class="card-header"><h5>Kalender Hari Libur</h5></div><div class="card-body"><form method="POST" action="{{ route($prefix.'master.jadwal-mingguan-holiday-store') }}" class="row g-2">@csrf<div class="col-md-4"><input name="nama" class="form-control" placeholder="Nama hari libur" required></div><div class="col-md-3"><input type="datetime-local" name="mulai_at" class="form-control" required></div><div class="col-md-3"><input type="datetime-local" name="selesai_at" class="form-control" required></div><div class="col-md-2"><button class="btn btn-outline-primary">Tambahkan</button></div></form>@if($holidays->isNotEmpty())<div class="mt-2"><small class="text-muted">Libur terpublikasi: {{ $holidays->map(fn($holiday) => $holiday->nama.' ('.$holiday->mulai_at->format('d M Y').')')->join(', ') }}</small></div>@endif</div></div>@endif
@if($previewSchedule)<div class="card mb-3 border-primary"><div class="card-header"><h5>Pratinjau Pertemuan — {{ $previewSchedule->penawaranMataKuliah->masterMataKuliah->name }}</h5></div><div class="card-body"><table class="table"><thead><tr><th>Ke</th><th>Tanggal</th><th>Status</th></tr></thead><tbody>@foreach($preview as $candidate)<tr><td>{{ $candidate['pertemuan_ke'] }}</td><td>{{ $candidate['tanggal'] }}</td><td>{{ $candidate['sudah_ada'] ? 'Duplikat — dilewati' : 'Akan dibuat' }}</td></tr>@endforeach</tbody></table><form method="POST" action="{{ route($prefix.'master.jadwal-mingguan-generate', $previewSchedule) }}">@csrf @foreach($generationInput as $key=>$value)<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endforeach<button class="btn btn-primary">Konfirmasi dan buat pertemuan</button></form></div></div>@endif
<div class="card"><div class="card-header d-flex flex-wrap justify-content-between gap-2"><h5>Jadwal Mingguan — {{ $period?->name ?? 'Periode belum dipilih' }}</h5>@if($period)<div class="d-flex flex-wrap gap-2"><form method="GET" action="{{ route($prefix.'master.jadwal-mingguan-print') }}" target="_blank" class="d-flex gap-2"><select name="pstudi_id" class="form-select" required><option value="">Pilih program studi</option>@foreach($studyPrograms as $studyProgram)<option value="{{ $studyProgram->id }}">{{ $studyProgram->name }}</option>@endforeach</select><button class="btn btn-outline-primary text-nowrap">Cetak Jadwal</button></form><a target="_blank" href="{{ route($prefix.'master.jadwal-mingguan-recap') }}" class="btn btn-outline-secondary text-nowrap">Cetak Rekap Presensi</a></div>@endif</div><div class="card-body table-responsive"><table class="table table-striped"><thead><tr><th>Mata Kuliah</th><th>Kelas</th><th>Dosen</th><th>Ruang</th><th>Hari/Jam</th><th>Pertemuan</th><th>Aksi</th></tr></thead><tbody>
@forelse($schedules as $schedule)<tr><td>{{ $schedule->penawaranMataKuliah?->masterMataKuliah?->name ?? 'Legacy' }}</td><td>{{ $schedule->kelas->name }}</td><td>{{ $schedule->dosen->dsn_name }}</td><td>{{ $schedule->ruang->name }}</td><td>{{ $schedule->hari_label }}<br>{{ $schedule->mulai }}–{{ $schedule->selesai }}</td><td>{{ $schedule->pertemuans->count() }}</td><td class="d-flex gap-1">@if($canManage)<button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#generate{{ $schedule->id }}">Generate</button><button class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#edit{{ $schedule->id }}">Edit</button><form method="POST" action="{{ route($prefix.'master.jadwal-mingguan-destroy', $schedule) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" onclick="return confirm('Hapus jadwal?')">Hapus</button></form>@endif</td></tr>@empty<tr><td colspan="7" class="text-center">Belum ada jadwal mingguan.</td></tr>@endforelse
</tbody></table></div></div>
@if($canManage)@foreach($schedules as $schedule)
<div class="modal fade" id="generate{{ $schedule->id }}"><div class="modal-dialog"><div class="modal-content"><form method="GET" action="{{ route($prefix.'master.jadwal-mingguan-preview', $schedule) }}"><div class="modal-header"><h5>Generator Pertemuan</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label>Mulai semester</label><input type="date" name="mulai_tanggal" value="{{ $period->starts_at?->toDateString() }}" class="form-control mb-2" required><label>Selesai semester</label><input type="date" name="selesai_tanggal" value="{{ $period->ends_at?->toDateString() }}" class="form-control mb-2" required><label>Jumlah pertemuan</label><input type="number" name="jumlah_pertemuan" value="16" min="1" max="20" class="form-control" required></div><div class="modal-footer"><button class="btn btn-primary">Pratinjau</button></div></form></div></div></div>
<div class="modal fade" id="edit{{ $schedule->id }}"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route($prefix.'master.jadwal-mingguan-update', $schedule) }}">@csrf @method('PATCH')<div class="modal-header"><h5>Edit Jadwal Mingguan</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><input type="hidden" name="penawaran_mata_kuliah_id" value="{{ $schedule->penawaran_mata_kuliah_id }}"><input type="hidden" name="kelas_id" value="{{ $schedule->kelas_id }}"><div class="col-12"><label>Dosen</label><select name="dosen_id" class="form-select">@foreach($lecturers as $lecturer)<option value="{{ $lecturer->id }}" @selected($lecturer->id===$schedule->dosen_id)>{{ $lecturer->dsn_name }}</option>@endforeach</select></div><div class="col-12"><label>Ruang</label><select name="ruang_id" class="form-select">@foreach($rooms as $room)<option value="{{ $room->id }}" @selected($room->id===$schedule->ruang_id)>{{ $room->name }} ({{ $room->kapasitas }})</option>@endforeach</select></div><div class="col-4"><label>Hari</label><select name="hari" class="form-select">@foreach(['Minggu','Senin','Selasa','Rabu','Kamis',"Jum'at",'Sabtu'] as $day)<option value="{{ $loop->index }}" @selected($loop->index===$schedule->hari)>{{ $day }}</option>@endforeach</select></div><div class="col-4"><label>Mulai</label><input type="time" name="mulai" value="{{ substr($schedule->mulai,0,5) }}" class="form-control"></div><div class="col-4"><label>Selesai</label><input type="time" name="selesai" value="{{ substr($schedule->selesai,0,5) }}" class="form-control"></div><div class="col-12"><input type="checkbox" name="override_conflict" value="1"> Pengecualian bentrok<textarea name="alasan_pengecualian" class="form-control mt-1">{{ $schedule->alasan_pengecualian }}</textarea></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div></div>
@endforeach @endif
</section>
@endsection
